# Generated by Django 3.0 on 2019-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191212_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=models.ImageField(blank=True, default='images/user-icon.png', help_text='User profile image', null=True, upload_to='images/'),
        ),
    ]
