# Generated by Django 3.0 on 2019-12-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191212_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=models.ImageField(default='images/user-icon.png', help_text='User profile image', upload_to='images/'),
        ),
    ]
