# Generated by Django 2.2.7 on 2019-11-18 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your note a title to remember.', max_length=600, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this note.Computer Generated.', max_length=600)),
                ('content', models.TextField(help_text='Log your observations, questions, and hypotheses here.')),
                ('media', models.ImageField(help_text='Optional image to add to note.', upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this note was created. Auto-generated.')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='The date and time this note was editied. Auto-calculated.')),
                ('author', models.ForeignKey(help_text='The explorer making this log.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
