# Generated by Django 2.2.7 on 2019-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191120_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.ImageField(help_text='Optional image to add to note.', upload_to=''),
        ),
    ]
