# Generated by Django 2.2.7 on 2019-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20191120_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.ImageField(blank=True, help_text='Optional image to add to note.', upload_to=''),
        ),
    ]
