# Generated by Django 2.2.7 on 2019-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191120_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(blank=True, help_text='Unique URL path to access this note.Computer Generated.', max_length=600),
        ),
    ]
