# Generated by Django 2.2.7 on 2019-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20191121_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this note.Computer Generated.', max_length=600),
        ),
    ]
