# Generated by Django 2.2.7 on 2019-11-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20191121_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(blank=True, help_text='Unique URL path to access this note.Computer Generated.', max_length=600),
        ),
    ]
