# Generated by Django 2.2.7 on 2019-11-23 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20191122_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time this note was created. Auto-generated.'),
            preserve_default=False,
        ),
    ]
