# Generated by Django 2.2.5 on 2019-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.ImageField(blank=True, help_text='Optional image to add to note.', upload_to='media/'),
        ),
    ]
