# Generated by Django 2.2.5 on 2019-11-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20191126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image to add to note.', upload_to='image/'),
        ),
    ]
