# Generated by Django 3.0 on 2019-12-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20191126_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image to add to note.', null=True, upload_to='image/'),
        ),
    ]
