# Generated by Django 3.0 on 2019-12-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20191204_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='media',
        ),
    ]
