# Generated by Django 3.0 on 2019-12-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_remove_note_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image to add to note.', null=True, upload_to='image/'),
        ),
    ]
