# Generated by Django 3.0 on 2019-12-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_note_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this note.Computer Generated.', max_length=600),
        ),
    ]
