# Generated by Django 3.0 on 2019-12-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_auto_20191204_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image to add to note.', null=True, upload_to='static/images/'),
        ),
    ]
