# Generated by Django 3.0 on 2019-12-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_auto_20191206_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.ImageField(blank=True, help_text='Optional image to add to note.', null=True, upload_to='images/'),
        ),
    ]
